"""
Authentication API Routes
- Login, signup, password reset with SQLAlchemy
- Email notifications for login, signup, password reset
"""
from flask import Blueprint, request, jsonify
import bcrypt
import jwt
import uuid
from datetime import datetime, timedelta
from config import config
from models import db, User, PasswordResetToken
from handlers import send_welcome_email, send_login_notification_email, send_password_reset_email

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['POST'])
def login():
    """Login with email and password"""
    data = request.get_json()
    email = data.get('email', '').strip().lower()
    password = data.get('password', '')
    
    if not email or not password:
        return jsonify({'error': 'Email and password required'}), 400
    
    # Find user by email
    user = User.query.filter_by(email=email).first()
    
    if not user:
        return jsonify({'error': 'Invalid credentials'}), 401
    
    # Verify password
    if not bcrypt.checkpw(password.encode('utf-8'), user.password.encode('utf-8')):
        return jsonify({'error': 'Invalid credentials'}), 401
    
    # Generate JWT token
    payload = {
        'user_id': user.id,
        'email': user.email,
        'role': user.role,
        'exp': datetime.utcnow() + timedelta(hours=config.JWT_EXPIRY_HOURS)
    }
    token = jwt.encode(payload, config.JWT_SECRET, algorithm='HS256')
    
    # Update last login
    user.last_login_at = datetime.utcnow()
    db.session.commit()
    
    # Send login notification email (async, don't block response)
    try:
        ip_address = request.headers.get('X-Forwarded-For', request.remote_addr or 'Unknown')
        user_agent = request.headers.get('User-Agent', 'Unknown device')
        send_login_notification_email(user.email, user.name, ip_address, user_agent)
    except Exception as e:
        print(f'[Auth] Login notification email failed: {e}')
    
    return jsonify({
        'user': user.to_dict(),
        'token': token
    })


@auth_bp.route('/signup', methods=['POST'])
def signup():
    """Register a new user"""
    data = request.get_json()
    name = data.get('name', '').strip()
    email = data.get('email', '').strip().lower()
    password = data.get('password', '')
    country_code = request.user_country
    
    if not name or not email or not password:
        return jsonify({'error': 'Name, email, and password required'}), 400
    
    if len(password) < 6:
        return jsonify({'error': 'Password must be at least 6 characters'}), 400
    
    # Check if email already exists
    existing = User.query.filter_by(email=email).first()
    if existing:
        return jsonify({'error': 'Email already registered'}), 400
    
    # Hash password
    password_hash = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
    
    # Create user (id is auto-generated by database)
    user = User(
        name=name,
        email=email,
        password=password_hash,
        role='user',
        country_code=country_code
    )
    
    db.session.add(user)
    db.session.commit()
    
    # Send welcome email (async, don't block response)
    try:
        send_welcome_email(user.email, user.name)
    except Exception as e:
        print(f'[Auth] Welcome email failed: {e}')
    
    return jsonify(user.to_dict()), 201


@auth_bp.route('/forgot-password', methods=['POST'])
def forgot_password():
    """Request password reset"""
    data = request.get_json()
    email = data.get('email', '').strip().lower()
    
    if not email:
        return jsonify({'error': 'Email required'}), 400
    
    # Check if user exists
    user = User.query.filter_by(email=email).first()
    
    # Always return success to prevent email enumeration
    if user:
        token_value = str(uuid.uuid4())
        reset_token = PasswordResetToken(
            user_id=user.id,
            token=token_value,
            expires_at=datetime.utcnow() + timedelta(hours=1)
        )
        db.session.add(reset_token)
        db.session.commit()
        
        # Send password reset email
        try:
            send_password_reset_email(user.email, user.name, token_value)
        except Exception as e:
            print(f'[Auth] Password reset email failed: {e}')
    
    return jsonify({'message': 'If email exists, reset link will be sent'})


@auth_bp.route('/reset-password', methods=['POST'])
def reset_password():
    """Reset password with token"""
    data = request.get_json()
    token = data.get('token', '')
    new_password = data.get('password', '')
    
    if not token or not new_password:
        return jsonify({'error': 'Token and password required'}), 400
    
    if len(new_password) < 6:
        return jsonify({'error': 'Password must be at least 6 characters'}), 400
    
    # Find valid token
    reset_token = PasswordResetToken.query.filter(
        PasswordResetToken.token == token,
        PasswordResetToken.expires_at > datetime.utcnow(),
        PasswordResetToken.used == False
    ).first()
    
    if not reset_token:
        return jsonify({'error': 'Invalid or expired token'}), 400
    
    # Update password
    user = User.query.get(reset_token.user_id)
    if user:
        user.password = bcrypt.hashpw(new_password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
        reset_token.used = True
        db.session.commit()
    
    return jsonify({'message': 'Password reset successful'})


@auth_bp.route('/me', methods=['GET'])
def get_current_user():
    """Get current user from token"""
    auth_header = request.headers.get('Authorization', '')
    
    if not auth_header.startswith('Bearer '):
        return jsonify({'error': 'No token provided'}), 401
    
    token = auth_header.split(' ')[1]
    
    try:
        payload = jwt.decode(token, config.JWT_SECRET, algorithms=['HS256'])
        user = User.query.get(payload['user_id'])
        
        if not user:
            return jsonify({'error': 'User not found'}), 404
        
        return jsonify(user.to_dict())
    except jwt.ExpiredSignatureError:
        return jsonify({'error': 'Token expired'}), 401
    except jwt.InvalidTokenError:
        return jsonify({'error': 'Invalid token'}), 401


@auth_bp.route('/google-signin', methods=['POST'])
def google_signin():
    """Login or signup with Google OAuth (syncs with Firebase)"""
    from handlers import send_google_login_email
    
    data = request.get_json()
    firebase_uid = data.get('firebase_uid', '')
    email = data.get('email', '').strip().lower()
    name = data.get('name', '').strip()
    avatar_url = data.get('avatarUrl', '')
    
    if not email:
        return jsonify({'error': 'Email required'}), 400
    
    # Check if user exists
    user = User.query.filter_by(email=email).first()
    
    if user:
        # Existing user - update Google/Firebase info if needed
        if firebase_uid and not user.firebase_uid:
            user.firebase_uid = firebase_uid
        if avatar_url and not user.avatar_url:
            user.avatar_url = avatar_url
        
        user.last_login_at = datetime.utcnow()
        db.session.commit()
        
        print(f'[Auth] ✅ Google login: {email}')
    else:
        # New user - create account
        user = User(
            name=name or email.split('@')[0],
            email=email,
            password='',  # No password for Google users
            role='user',
            firebase_uid=firebase_uid,
            avatar_url=avatar_url,
            email_verified=True,  # Google verified
            email_verified_at=datetime.utcnow(),
            country_code=request.user_country
        )
        db.session.add(user)
        db.session.commit()
        
        print(f'[Auth] ✅ New Google signup: {email}')
        
        # Send welcome email for new users
        try:
            send_welcome_email(user.email, user.name)
        except Exception as e:
            print(f'[Auth] ❌ Welcome email failed: {e}')
    
    # Generate JWT token
    payload = {
        'user_id': user.id,
        'email': user.email,
        'role': user.role,
        'exp': datetime.utcnow() + timedelta(hours=config.JWT_EXPIRY_HOURS)
    }
    token = jwt.encode(payload, config.JWT_SECRET, algorithm='HS256')
    
    # Send Google login notification email
    try:
        ip_address = request.headers.get('X-Forwarded-For', request.remote_addr or 'Unknown')
        user_agent = request.headers.get('User-Agent', 'Unknown device')
        send_google_login_email(user.email, user.name, ip_address, user_agent)
    except Exception as e:
        print(f'[Auth] ❌ Google login email failed: {e}')
    
    return jsonify({
        'user': user.to_dict(),
        'token': token
    })
