"""create user_investment_goals table

Revision ID: 07866c2f7ee9
Revises: add_user_notif_unique
Create Date: 2026-01-27 18:02:28.063968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07866c2f7ee9'
down_revision = 'add_user_notif_unique'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_investment_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('target_stocks_percent', sa.Integer(), nullable=True),
    sa.Column('target_bonds_percent', sa.Integer(), nullable=True),
    sa.Column('target_cash_percent', sa.Integer(), nullable=True),
    sa.Column('target_crypto_percent', sa.Integer(), nullable=True),
    sa.Column('target_commodities_percent', sa.Integer(), nullable=True),
    sa.Column('risk_tolerance', sa.Enum('conservative', 'moderate', 'aggressive'), nullable=True),
    sa.Column('benchmark_symbol', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_investment_goals')
    # ### end Alembic commands ###
