"""Add performance indexes

Revision ID: 190542071fa7
Revises: 07866c2f7ee9
Create Date: 2026-01-30 18:09:00.961840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '190542071fa7'
down_revision = '07866c2f7ee9'
branch_labels = None
depends_on = None


def upgrade():
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_index('idx_news_source')
        batch_op.drop_index('idx_news_feed')
        batch_op.drop_index('idx_news_category')

    with op.batch_alter_table('market_data', schema=None) as batch_op:
        batch_op.drop_index('idx_market_volume')
        batch_op.drop_index('idx_market_movers')
        batch_op.drop_index('idx_market_country')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index('idx_course_filter')
        batch_op.drop_index('idx_course_category')

    # ### end Alembic commands ###

    # ### end Alembic commands ###
