"""add sector to market_data

Revision ID: 2d2049edf8e1
Revises: 
Create Date: 2026-01-12 17:49:27.969055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d2049edf8e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sector', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('industry', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('open_price', sa.Numeric(precision=18, scale=6), nullable=True))
        batch_op.add_column(sa.Column('previous_close', sa.Numeric(precision=18, scale=6), nullable=True))
        batch_op.add_column(sa.Column('day_high', sa.Numeric(precision=18, scale=6), nullable=True))
        batch_op.add_column(sa.Column('day_low', sa.Numeric(precision=18, scale=6), nullable=True))
        batch_op.add_column(sa.Column('avg_volume', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('beta', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('forward_pe', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('trailing_pe', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('eps', sa.Numeric(precision=18, scale=6), nullable=True))
        batch_op.add_column(sa.Column('dividend_yield', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('dividend_rate', sa.Numeric(precision=18, scale=6), nullable=True))
        batch_op.add_column(sa.Column('book_value', sa.Numeric(precision=18, scale=6), nullable=True))
        batch_op.add_column(sa.Column('price_to_book', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('shares_outstanding', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('float_shares', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('short_ratio', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('logo_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('stock_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exchange', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('deal_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('shares_offered', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('offer_price', sa.Numeric(precision=18, scale=6), nullable=True))
    
   

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_offers', schema=None) as batch_op:
        batch_op.drop_column('offer_price')
        batch_op.drop_column('shares_offered')
        batch_op.drop_column('deal_type')
        batch_op.drop_column('exchange')

    with op.batch_alter_table('market_data', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('website')
        batch_op.drop_column('logo_url')
        batch_op.drop_column('short_ratio')
        batch_op.drop_column('float_shares')
        batch_op.drop_column('shares_outstanding')
        batch_op.drop_column('price_to_book')
        batch_op.drop_column('book_value')
        batch_op.drop_column('dividend_rate')
        batch_op.drop_column('dividend_yield')
        batch_op.drop_column('eps')
        batch_op.drop_column('trailing_pe')
        batch_op.drop_column('forward_pe')
        batch_op.drop_column('beta')
        batch_op.drop_column('avg_volume')
        batch_op.drop_column('day_low')
        batch_op.drop_column('day_high')
        batch_op.drop_column('previous_close')
        batch_op.drop_column('open_price')
        batch_op.drop_column('industry')
        batch_op.drop_column('sector')

    # ### end Alembic commands ###
