"""Add ytd_return to MarketData

Revision ID: 3498e773c4a8
Revises: aa4cd25b5c24
Create Date: 2026-02-06 15:04:41.265171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3498e773c4a8'
down_revision = 'aa4cd25b5c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index('idx_course_category', ['is_published', 'category'], unique=False)
        batch_op.create_index('idx_course_filter', ['is_published', 'country_code'], unique=False)

    with op.batch_alter_table('financial_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))

    with op.batch_alter_table('market_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ytd_return', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.create_index('idx_market_country', ['country_code', 'asset_type'], unique=False)
        batch_op.create_index('idx_market_movers', ['asset_type', 'is_listed', 'change_percent'], unique=False)
        batch_op.create_index('idx_market_volume', ['asset_type', 'is_listed', 'volume'], unique=False)

    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.create_index('idx_news_category', ['status', 'category', 'published_at'], unique=False)
        batch_op.create_index('idx_news_feed', ['status', 'published_at'], unique=False)
        batch_op.create_index('idx_news_source', ['source_type', 'status'], unique=False)

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('services', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True))
        batch_op.add_column(sa.Column('review_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('metadata', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('metadata')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('review_count')
        batch_op.drop_column('rating')
        batch_op.drop_column('services')
        batch_op.drop_column('category')

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_index('idx_news_source')
        batch_op.drop_index('idx_news_feed')
        batch_op.drop_index('idx_news_category')

    with op.batch_alter_table('market_data', schema=None) as batch_op:
        batch_op.drop_index('idx_market_volume')
        batch_op.drop_index('idx_market_movers')
        batch_op.drop_index('idx_market_country')
        batch_op.drop_column('ytd_return')

    with op.batch_alter_table('financial_goals', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index('idx_course_filter')
        batch_op.drop_index('idx_course_category')

    # ### end Alembic commands ###
