"""add business profile tables and columns

Revision ID: 353ad9168937
Revises: 1f0ec4921d3b
Create Date: 2026-01-17 13:11:05.749101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '353ad9168937'
down_revision = '1f0ec4921d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_financials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period', sa.Enum('annual', 'quarterly'), nullable=True))
        batch_op.add_column(sa.Column('fiscal_date_ending', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('ebitda', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('shareholder_equity', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('cash_and_equivalents', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('total_debt', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('operating_cash_flow', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('capital_expenditure', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('free_cash_flow', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('eps_actual', sa.Numeric(precision=18, scale=6), nullable=True))
        batch_op.add_column(sa.Column('eps_estimate', sa.Numeric(precision=18, scale=6), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('uq_symbol_year'))
        batch_op.drop_column('year')
        batch_op.drop_column('last_updated')

    with op.batch_alter_table('market_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_listed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.alter_column('asset_type',
               existing_type=mysql.ENUM('stock', 'crypto', 'forex', 'commodity', 'index', 'etf'),
               nullable=True,
               existing_server_default=sa.text("'stock'"))
        batch_op.create_index(batch_op.f('ix_market_data_is_listed'), ['is_listed'], unique=False)

    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_symbol', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_news_items_related_symbol'), ['related_symbol'], unique=False)

    with op.batch_alter_table('user_enrollments', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('enrolled', 'in_progress', 'paused', 'completed', 'unenrolled'),
               type_=sa.Enum('enrolled', 'in_progress', 'completed', 'paused', 'unenrolled'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_enrollments', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('enrolled', 'in_progress', 'completed', 'paused', 'unenrolled'),
               type_=mysql.ENUM('enrolled', 'in_progress', 'paused', 'completed', 'unenrolled'),
               nullable=False)

    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_items_related_symbol'))
        batch_op.drop_column('related_symbol')

    with op.batch_alter_table('market_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_data_is_listed'))
        batch_op.alter_column('asset_type',
               existing_type=mysql.ENUM('stock', 'crypto', 'forex', 'commodity', 'index', 'etf'),
               nullable=False,
               existing_server_default=sa.text("'stock'"))
        batch_op.drop_column('is_featured')
        batch_op.drop_column('is_listed')

    with op.batch_alter_table('company_financials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('uq_symbol_year'), ['symbol', 'year'], unique=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('currency')
        batch_op.drop_column('eps_estimate')
        batch_op.drop_column('eps_actual')
        batch_op.drop_column('free_cash_flow')
        batch_op.drop_column('capital_expenditure')
        batch_op.drop_column('operating_cash_flow')
        batch_op.drop_column('total_debt')
        batch_op.drop_column('cash_and_equivalents')
        batch_op.drop_column('shareholder_equity')
        batch_op.drop_column('ebitda')
        batch_op.drop_column('fiscal_date_ending')
        batch_op.drop_column('period')

    # ### end Alembic commands ###
