"""Add navigation item fields: section, link_type, badge_text, css_class, timestamps

Revision ID: a4dc73c03f36
Revises: 353ad9168937
Create Date: 2026-01-20 21:39:02.539318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4dc73c03f36'
down_revision = '353ad9168937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('analyst_recommendations', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('idx_date'))
    #     batch_op.drop_index(batch_op.f('idx_symbol'))
    #     batch_op.create_index(batch_op.f('ix_analyst_recommendations_symbol'), ['symbol'], unique=False)

    # with op.batch_alter_table('bulk_transactions', schema=None) as batch_op:
    #     batch_op.alter_column('country_code',
    #            existing_type=mysql.VARCHAR(length=5),
    #            type_=sa.String(length=10),
    #            existing_nullable=True)

    # with op.batch_alter_table('dividends', schema=None) as batch_op:
    #     batch_op.alter_column('country_code',
    #            existing_type=mysql.VARCHAR(length=5),
    #            type_=sa.String(length=10),
    #            existing_nullable=True)

    # with op.batch_alter_table('earnings_calendar', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('idx_earnings_date'))
    #     batch_op.drop_index(batch_op.f('idx_symbol'))
    #     batch_op.create_index(batch_op.f('ix_earnings_calendar_symbol'), ['symbol'], unique=False)

    # with op.batch_alter_table('job_listings', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('country_code', sa.String(length=10), nullable=True))

    # with op.batch_alter_table('market_data', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_market_data_is_listed'), ['is_listed'], unique=False)

    # with op.batch_alter_table('marketing_campaigns', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('country_code', sa.String(length=10), nullable=True))

    with op.batch_alter_table('navigation_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('link_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('badge_text', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('css_class', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # with op.batch_alter_table('news_items', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_news_items_related_symbol'), ['related_symbol'], unique=False)

    # with op.batch_alter_table('stock_price_history', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('idx_date'))
    #     batch_op.drop_index(batch_op.f('idx_symbol'))
    #     batch_op.create_index(batch_op.f('ix_stock_price_history_date'), ['date'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_stock_price_history_symbol'), ['symbol'], unique=False)

    # with op.batch_alter_table('stock_splits', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('idx_split_date'))
    #     batch_op.drop_index(batch_op.f('idx_symbol'))
    #     batch_op.create_index(batch_op.f('ix_stock_splits_symbol'), ['symbol'], unique=False)

    # with op.batch_alter_table('tasks', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('country_code', sa.String(length=10), nullable=True))

    # with op.batch_alter_table('user_alerts', schema=None) as batch_op:
    #     batch_op.alter_column('id',
    #            existing_type=mysql.VARCHAR(length=36),
    #            type_=sa.String(length=255),
    #            existing_nullable=False)

    # with op.batch_alter_table('webinars', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('country_code', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webinars', schema=None) as batch_op:
        batch_op.drop_column('country_code')

    with op.batch_alter_table('user_alerts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('country_code')

    with op.batch_alter_table('stock_splits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_splits_symbol'))
        batch_op.create_index(batch_op.f('idx_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('idx_split_date'), ['split_date'], unique=False)

    with op.batch_alter_table('stock_price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_price_history_symbol'))
        batch_op.drop_index(batch_op.f('ix_stock_price_history_date'))
        batch_op.create_index(batch_op.f('idx_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('idx_date'), ['date'], unique=False)

    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_items_related_symbol'))

    with op.batch_alter_table('navigation_items', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('css_class')
        batch_op.drop_column('badge_text')
        batch_op.drop_column('link_type')
        batch_op.drop_column('section')

    with op.batch_alter_table('marketing_campaigns', schema=None) as batch_op:
        batch_op.drop_column('country_code')

    with op.batch_alter_table('market_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_data_is_listed'))

    with op.batch_alter_table('job_listings', schema=None) as batch_op:
        batch_op.drop_column('country_code')

    with op.batch_alter_table('earnings_calendar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_earnings_calendar_symbol'))
        batch_op.create_index(batch_op.f('idx_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('idx_earnings_date'), ['earnings_date'], unique=False)

    with op.batch_alter_table('dividends', schema=None) as batch_op:
        batch_op.alter_column('country_code',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)

    with op.batch_alter_table('bulk_transactions', schema=None) as batch_op:
        batch_op.alter_column('country_code',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=5),
               existing_nullable=True)

    with op.batch_alter_table('analyst_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyst_recommendations_symbol'))
        batch_op.create_index(batch_op.f('idx_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('idx_date'), ['date'], unique=False)

    # ### end Alembic commands ###
