"""Add unique constraint to market_data symbol_country_asset

Revision ID: a9db0c863f73
Revises: 152a4197f570
Create Date: 2026-01-23 23:57:46.566920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9db0c863f73'
down_revision = '152a4197f570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_data', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_market_data_symbol_country_asset', ['symbol', 'country_code', 'asset_type'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_data', schema=None) as batch_op:
        batch_op.drop_constraint('uq_market_data_symbol_country_asset', type_='unique')

    # ### end Alembic commands ###
