"""Add CoursePurchase model

Revision ID: b61b3c014e80
Revises: b6ca6ec4f192
Create Date: 2026-03-01 14:22:10.705460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b61b3c014e80'
down_revision = 'b6ca6ec4f192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_encrypted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('sports_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('country_code',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_sports_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sports_events_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sports_events_sport_type'), ['sport_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sports_events_status'), ['status'], unique=False)

    with op.batch_alter_table('vendor_history', schema=None) as batch_op:
        batch_op.create_unique_constraint('_vendor_metric_uc', ['vendor_id', 'metric_type', 'recorded_at'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_history', schema=None) as batch_op:
        batch_op.drop_constraint('_vendor_metric_uc', type_='unique')

    with op.batch_alter_table('sports_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sports_events_status'))
        batch_op.drop_index(batch_op.f('ix_sports_events_sport_type'))
        batch_op.drop_index(batch_op.f('ix_sports_events_external_id'))
        batch_op.drop_index(batch_op.f('ix_sports_events_event_date'))
        batch_op.alter_column('country_code',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('external_id')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('is_encrypted')

    # ### end Alembic commands ###
