"""Add enhanced company financials fields

Revision ID: b871fdaaa93c
Revises: a4dc73c03f36
Create Date: 2026-01-21 21:44:28.692027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b871fdaaa93c'
down_revision = 'a4dc73c03f36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_financials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_of_revenue', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('selling_general_admin', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('research_development', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('operating_expenses', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('interest_expense', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('interest_income', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('pretax_income', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('income_tax', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('net_income_common', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('ebit', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('eps_basic', sa.Numeric(precision=18, scale=6), nullable=True))
        batch_op.add_column(sa.Column('eps_diluted', sa.Numeric(precision=18, scale=6), nullable=True))
        batch_op.add_column(sa.Column('shares_basic', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('shares_diluted', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('gross_margin', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('operating_margin', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('profit_margin', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('short_term_investments', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('accounts_receivable', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('inventory', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('current_assets', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('property_plant_equipment', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('long_term_investments', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('goodwill', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('intangible_assets', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('accounts_payable', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('short_term_debt', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('current_liabilities', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('long_term_debt', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('common_stock', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('retained_earnings', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('working_capital', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('net_cash', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('depreciation_amortization', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('stock_based_compensation', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('change_in_working_capital', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('investing_cash_flow', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('debt_issued', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('debt_repaid', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('dividends_paid', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('stock_repurchased', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('financing_cash_flow', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('net_cash_flow', sa.BigInteger(), nullable=True))
        batch_op.create_unique_constraint('uq_financials_symbol_period_date', ['symbol', 'period', 'fiscal_date_ending'])
        batch_op.drop_column('eps_estimate')
        batch_op.drop_column('eps_actual')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_financials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eps_actual', mysql.DECIMAL(precision=18, scale=6), nullable=True))
        batch_op.add_column(sa.Column('eps_estimate', mysql.DECIMAL(precision=18, scale=6), nullable=True))
        batch_op.drop_constraint('uq_financials_symbol_period_date', type_='unique')
        batch_op.drop_column('net_cash_flow')
        batch_op.drop_column('financing_cash_flow')
        batch_op.drop_column('stock_repurchased')
        batch_op.drop_column('dividends_paid')
        batch_op.drop_column('debt_repaid')
        batch_op.drop_column('debt_issued')
        batch_op.drop_column('investing_cash_flow')
        batch_op.drop_column('change_in_working_capital')
        batch_op.drop_column('stock_based_compensation')
        batch_op.drop_column('depreciation_amortization')
        batch_op.drop_column('net_cash')
        batch_op.drop_column('working_capital')
        batch_op.drop_column('retained_earnings')
        batch_op.drop_column('common_stock')
        batch_op.drop_column('long_term_debt')
        batch_op.drop_column('current_liabilities')
        batch_op.drop_column('short_term_debt')
        batch_op.drop_column('accounts_payable')
        batch_op.drop_column('intangible_assets')
        batch_op.drop_column('goodwill')
        batch_op.drop_column('long_term_investments')
        batch_op.drop_column('property_plant_equipment')
        batch_op.drop_column('current_assets')
        batch_op.drop_column('inventory')
        batch_op.drop_column('accounts_receivable')
        batch_op.drop_column('short_term_investments')
        batch_op.drop_column('profit_margin')
        batch_op.drop_column('operating_margin')
        batch_op.drop_column('gross_margin')
        batch_op.drop_column('shares_diluted')
        batch_op.drop_column('shares_basic')
        batch_op.drop_column('eps_diluted')
        batch_op.drop_column('eps_basic')
        batch_op.drop_column('ebit')
        batch_op.drop_column('net_income_common')
        batch_op.drop_column('income_tax')
        batch_op.drop_column('pretax_income')
        batch_op.drop_column('interest_income')
        batch_op.drop_column('interest_expense')
        batch_op.drop_column('operating_expenses')
        batch_op.drop_column('research_development')
        batch_op.drop_column('selling_general_admin')
        batch_op.drop_column('cost_of_revenue')

    # ### end Alembic commands ###
