"""news preferences and notifications tables

Revision ID: f6138add059d
Revises: a9db0c863f73
Create Date: 2026-01-26 17:59:02.650980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6138add059d'
down_revision = 'a9db0c863f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_notification_prefs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_security', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_account', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_price_alerts', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_daily_digest', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_earnings', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_newsletter', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('push_security', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('push_price_alerts', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('push_earnings', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sms_security', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sms_price_alerts', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('quiet_hours_start', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('quiet_hours_end', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_notification_prefs', schema=None) as batch_op:
        batch_op.drop_column('quiet_hours_end')
        batch_op.drop_column('quiet_hours_start')
        batch_op.drop_column('quiet_hours_enabled')
        batch_op.drop_column('sms_price_alerts')
        batch_op.drop_column('sms_security')
        batch_op.drop_column('push_earnings')
        batch_op.drop_column('push_price_alerts')
        batch_op.drop_column('push_security')
        batch_op.drop_column('email_newsletter')
        batch_op.drop_column('email_earnings')
        batch_op.drop_column('email_daily_digest')
        batch_op.drop_column('email_price_alerts')
        batch_op.drop_column('email_account')
        batch_op.drop_column('email_security')

    # ### end Alembic commands ###
